x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.0-python3.11
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    PYTHONPATH: /opt/airflow/src
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src  # Montamos tu código ETL
    - ./config_file:/opt/airflow/config_file
  user: "${AIRFLOW_UID:-50000}"
  depends_on:
    airflow-db:
      condition: service_healthy

services:
  # Base de datos para Airflow (metadata)
  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  # Inicializa la DB de Airflow
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    restart: on-failure

  # Webserver
  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver

  # Scheduler
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  # Worker
  airflow-worker:
    <<: *airflow-common
    command: celery

  # Base de datos ETL (la tuya)
  pokemon-db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pikachu15
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - pokemon_db_data:/var/lib/postgresql/data

  # pgAdmin para gestionar la DB
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pokemon-db

volumes:
  airflow_db_data:
  pokemon_db_data:
